---
- name: Download and install Zabbix repository package
  command: >
    rpm -Uvh https://repo.zabbix.com/zabbix/{{ zabbix_version }}/rhel/{{ ansible_distribution_major_version }}/x86_64/zabbix-release-latest-{{ zabbix_version }}.el{{ ansible_distribution_major_version }}.noarch.rpm
  args:
    warn: false

- name: Clean YUM cache
  command: yum clean all
  ignore_errors: yes

- name: Update YUM cache
  yum:
    update_cache: yes

- name: Install Zabbix Agent
  yum:
    name: zabbix-agent
    state: present

- name: Configure Zabbix Agent to use specified Zabbix server
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: "^Server=.*"
    line: "Server={{ zabbix_server }}"
    backup: yes

- name: Configure Zabbix Agent hostname
  lineinfile:
    path: /etc/zabbix/zabbix_agentd.conf
    regexp: "^Hostname=.*"
    line: "Hostname={{ inventory_hostname }}"
    backup: yes

- name: Ensure Zabbix directories exist
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  with_items:
    - /etc/zabbix/scripts
    - /etc/zabbix/zabbix_agentd.d

- name: Copy scripts to /etc/zabbix/scripts
  copy:
    src: "scripts/"
    dest: "/etc/zabbix/scripts/"
    owner: root
    group: root
    mode: '0755'

- name: Copy configuration files to /etc/zabbix/zabbix_agentd.d
  copy:
    src: "zabbix_agentd.d/"
    dest: "/etc/zabbix/zabbix_agentd.d/"
    owner: root
    group: root
    mode: '0644'


- name: Enable and start Zabbix Agent
  systemd:
    name: zabbix-agent
    enabled: "{{ zabbix_agent_enabled | default(true) }}"
    state: "{{ zabbix_agent_state | default('started') }}"
