version: '3.5'
services:
  mysql-server:
    image: mysql:8.0
    command:
      - mysqld
      - --character-set-server=utf8
      - --collation-server=utf8_bin
      - --default-authentication-plugin=mysql_native_password
      - --log_bin_trust_function_creators=1   # Allow function creation without SUPER privilege
    environment:
      - MYSQL_USER=zabbix
      - MYSQL_DATABASE=zabbixdb
      - MYSQL_PASSWORD=Password
      - MYSQL_ROOT_PASSWORD=Password
    volumes:
      - '/root/db/data:/var/lib/mysql'
      - '/root/db/my.cnf:/etc/mysql/conf.d/my.cnf'
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /zabbix-mysql:/zabbix-mysql
  
  zabbix-server-mysql:
    image: zabbix/zabbix-server-mysql:ubuntu-7.0-latest
    ports:
      - 10051:10051
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro 
      - /zabbix-data/alertscripts:/usr/lib/zabbix/alertscripts:ro
      - /zabbix-data/externalscripts:/usr/lib/zabbix/externalscripts:ro
      - /zabbix-data/export:/var/lib/zabbix/export:rw
      - /zabbix-data/modules:/var/lib/zabbix/modules:ro
      - /zabbix-data/enc:/var/lib/zabbix/enc:ro
      - /zabbix-data/ssh_keys:/var/lib/zabbix/ssh_keys:ro
      - /zabbix-data/mibs:/var/lib/zabbix/mibs:ro
      - /zabbix-data/snmptraps:/var/lib/zabbix/snmptraps:rw
    environment:
      - DB_SERVER_HOST=mysql-server
      - MYSQL_DATABASE=zabbixdb
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=Password
      - MYSQL_ROOT_PASSWORD=Password
      - ZBX_JAVAGATEWAY=zabbix-java-gateway
      - ZBX_CACHESIZE=3G
      - ZBX_VALUECACHESIZE=2G
    depends_on:
      - mysql-server

  zabbix-web-nginx-mysql:
    image: zabbix/zabbix-web-nginx-mysql:ubuntu-7.0-latest
    ports:
      - 80:8080
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /zabbix-nginx/modules/:/usr/share/zabbix/modules/:ro
    environment:
      - ZBX_SERVER_HOST=zabbix-server-mysql
      - DB_SERVER_HOST=mysql-server
      - MYSQL_DATABASE=zabbixdb
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=Password
      - MYSQL_ROOT_PASSWORD=Password
    depends_on:
      - mysql-server
      - zabbix-server-mysql

  zabbix-java-gateway:
    image: zabbix/zabbix-java-gateway:ubuntu-7.0-latest
    ports:
      - 10052:10052
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

